version: '3'

services:

  # Star Postgres, and ensure that data is stored to a mounted volumn
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vueapi
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  # Start Mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always